# /wordpress-docker/docker-compose.yml
---
version: '3.3'
services:
    db:
      image: mysql:5.7
      volumes:
        - ./data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      ports:
        - ${APP_PORT}:80
      restart: always
      volumes:
        - "./wordpress:/var/www/html"
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
